spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         - name: GC_MAX_METASPACE_SIZE
           value: '200'
         - name: AB_JOLOKIA_OFF
           value: 'true'
         - name: AB_OFF
           value: 'true'
        resources:
          limits:
            memory: 512Mi
