apiVersion: v1
kind: "Deployment"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         - name: JAVA_OPTIONS
           value: "-Xmx512m -Dswarm.bind.address=0.0.0.0"
        resources:
          limits:
            memory: 1024Mi
