spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         - name: JAVA_OPTIONS
           value: "-Dswarm.project.stage.file=file:///app/config/project-defaults.yml"
         - name: GC_MAX_METASPACE_SIZE
           value: '200'
         - name: AB_JOLOKIA_OFF
           value: 'true'
         - name: AB_OFF
           value: 'true'
        resources:
          limits:
            memory: 1024Mi
        volumeMounts:
         - name: config
           mountPath: /app/config
      volumes:
        - configMap:
            name: app-config
          name: config