---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
         - name: JAVA_OPTIONS
           value: "-Xmx512m -Dswarm.bind.address=0.0.0.0 -Dswarm.project.stage.file=file:///app/config/project-defaults.yml"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /app/config
          name: appconfigvol
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: appconfigcm
        name: appconfigvol
