apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    hystrix.enabled: true
    hystrix.cluster: hola
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
