---
apiVersion: v1
kind: ConfigMap
data:
  HOLA_SERVICE_URL: http://hola-hello-gateway.apps.lab.example.com/api
  BONJOUR_SERVICE_URL: http://bonjour-hello-gateway.apps.lab.example.com/api
metadata:
  name: app-config
