apiVersion: v1
kind: Route
metadata:
  name: api-gateway
spec:
  host: api-gateway.apps.lab.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: api-gateway
    weight: 100
  wildcardPolicy: None
